project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!vezbe/**"
    - "!01_tidyverse/**"

  resources:
    - vezbe/
    - 01_tidyverse/
    
website:
  title: "Analiza prostorno-vremenskih podataka"
  navbar:
    left:
      - href: index.qmd
        text: Početna
    right:
      - icon: github
        href: https://github.com/milankili/AnalizaProstornoVremenskihPodataka
        
execute:
    freeze: auto
    cache: true
    
format:
  html:
    theme: cosmo
    toc: false
    smooth-scroll: true
  
