---
title: "Analiza prostorno-vremenskih podataka"
---

## O kursu

Ovde možete pronaći materijale za predmet **Analiza prostorno-vremenskih podataka**. Ovaj materijal je namenjen za Master studije geoinformatike na Građevinskom fakultetu u Beogradu, 2026. godine.

Vežbe su na linku [https://github.com/milankili/AnalizaProstornoVremenskihPodataka/tree/main/vezbe](https://github.com/milankili/AnalizaProstornoVremenskihPodataka/tree/main/vezbe)

Podaci za vežbe i predavanja su dostupni na [https://github.com/milankili/AnalizaProstornoVremenskihPodataka/tree/main/data](https://github.com/milankili/AnalizaProstornoVremenskihPodataka/tree/main/data)


---

## Prezentacije 

::: {.grid}

::: {.g-col-12 .g-col-md-6}
::: {.card .h-100 .shadow-sm .p-3}

### ️ Tipovi prostornih podataka u R jeziku

Uvodna prezentacija sa pregledom tipova prostornih podataka u R-u, osnovnim paketima i strukturama.

<br>
[Otvori prezentaciju]("02_introSpatial/p1.html"){.btn .btn-primary role="button"}

:::
:::

::: {.g-col-12 .g-col-md-6}
::: {.card .h-100 .shadow-sm .p-3}

### ️Uvod  u R 

Uvodna prezentacija za R.

<br>
[Otvori prezentaciju](00_R/Uvod_u_R.html){.btn .btn-primary role="button"}

:::
:::

::: {.g-col-12 .g-col-md-6}
::: {.card .h-100 .shadow-sm .p-3}

### ️Uvod  u Tidyverse 

Uvodna prezentacija za Tidyverse. U ovoj prezentaciji su predstavljeni ključni paketi poput ggplot2, za vizualizaciju, dplyr i tidyr, za manipulaciju, kao i readr, za uvoz podataka.

<br>
[Otvori prezentaciju](01_tidyverse/tidyverse.html){.btn .btn-primary role="button"}

:::
:::


::: {.g-col-12 .g-col-md-6}
::: {.card .h-100 .shadow-sm .p-3}

### ️Uvod u sf paket 

Ovaj izvor predstavlja sveobuhvatan vodič za korišćenje sf paketa u programskom jeziku R, koji je dizajniran za efikasan rad sa prostornim vektorskim podacima. Prezentacija pokriva ključne funkcionalnosti sf paketa, uključujući kreiranje, manipulaciju i analizu prostornih objekata, kao i integraciju sa drugim R paketima za prostornu analizu.

<br>
[Otvori prezentaciju](03_sf/sf.html){.btn .btn-primary role="button"}

:::
:::


::: {.g-col-12 .g-col-md-6}
::: {.card .h-100 .shadow-sm .p-3}

### ️Uvod R terra paket 

Upoznajemo se sa paketom terra u programskom jeziku R, modernim i optimizovanim standardom za obradu i analizu rasterskih prostornih podataka. Prezentacija pokriva ključne funkcionalnosti terra paketa, uključujući kreiranje, manipulaciju i analizu raster objekata, kao i integraciju sa drugim R paketima za prostornu analizu.

<br>
[Otvori prezentaciju](04_terra/terra.html){.btn .btn-primary role="button"}

:::
:::



:::
---

## Preporučena literatura

Materijali i analize pokrivene na ovim predavanjima u velikoj meri se oslanjaju na sledeću literaturu:

* **Pebesma, E., & Bivand, R. (2023).** *Spatial Data Science: With Applications in R*. Chapman and Hall/CRC. 
  * Dostupno na: [https://r-spatial.org/book/](https://r-spatial.org/book/)
* **Wickham, H., Çetinkaya-Rundel, M., & Grolemund, G. (2023).** *R for Data Science* (2nd ed.). O'Reilly Media. 
  * Dostupno na: [https://r4ds.hadley.nz/](https://r4ds.hadley.nz/)
* **Moraga, P. (2023).** *Spatial Statistics for Data Science: Theory and Practice with R*. Chapman and Hall/CRC. 
  * Dostupno na: [https://www.paulamoraga.com/book-spatial/](https://www.paulamoraga.com/book-spatial/)
* **Camara, G., Simoes, R., Souza, F., Carlos, F., Andrade, P., Ferreira, K., Brito, P., Assunção, A., & Pelletier, C. (2024).** *Satellite Image Time Series Analysis on Earth Observation Data Cubes*. 
  * Dostupno na: [https://e-sensing.github.io/sitsbook/](https://e-sensing.github.io/sitsbook/)
* **Sekulić, A., Kilibarda, M., Heuvelink, G. B., Nikolić, M., & Bajat, B. (2020).** *Random Forest Spatial Interpolation*. Remote Sensing, 12(10), 1687. 
  * Dostupno na: [https://www.mdpi.com/2072-4292/12/10/1687](https://www.mdpi.com/2072-4292/12/10/1687)
* **Kilibarda, M.** *Matematička kartografija*. 
  * Dostupno na: [https://osgl.grf.bg.ac.rs/books/mk/](https://osgl.grf.bg.ac.rs/books/mk/)

---

::: {.callout-note appearance="simple" icon="false"}
## Napomena
Nove prezentacije i materijali će biti dodavani u kontinuitetu tokom godine.
:::